# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - consoles:
      layout: tiled
      panes:
        - 1:
          - ssh dev
          - cd frontend
          - foreman start
        - 2:
          - ssh dev
          - cd backend
          - foreman start
        - 3:
          - ssh dev
          - cd frontend
          - rails c
        - 4:
          - ssh dev
          - cd backend
          - bin/logikcull console -E development
  - dirs:
      layout: even-horizontal
      panes:
        - 1:
          - ssh dev
          - cd frontend
        - 2:
          - ssh dev
          - cd backend
