# ~/.tmuxinator/dev4.yml

name: dev
root: ~/

windows:
  - dev:
      layout: even-horizontal
      panes:
        - 1:
          - ssh dev
          - cd frontend
        - 2:
          - ssh dev
          - cd backend
