# ~/.tmuxinator/dev4.yml

name: prod
root: ~/

windows:
  - dev:
      layout: even-horizontal
      panes:
        - 1:
          - ssh fe0001
          - cd frontend
        - 2:
          - ssh str0001
          - cd backend
